### PR TITLE
BOLO and General Diagnostic

### PR DESCRIPTION
**Pull request by nicolavianello**
Hi David
I've implemented and checked the BOLO diagnostic which handle properly the choice of LoS and have part of the geometrical information of the LoS saved as attributed. There is also a general diagnostic for the general signal which can be used. Give a look if they work
Cheers
Nicola

### CODE REVIEW

**Comment by wagdav** [comment]
Hello,

Can you please correct the failing tests? There seems to be some issues with the formatting:

https://travis-ci.org/wagdav/tcvpy/jobs/126059337#L191

Thanks!

**Comment by nicolavianello** [comment]
Hi David I've checked now with autopep8 and should work and be PEP8 compliant
Cheers
nicola

**Comment by nicolavianello** [comment]
Sorry David again there were two lines too long (I can't understand why autopep8 did not check for them)

**Comment by wagdav** [comment]
Hello,

Thanks for the pull request, I've merged this branch. Look good to me! I opened additional issues for further work see #15

**Pull request merged**
